using FluentMigrator;
using FluentMigrator.Expressions;

namespace MindEarth.Web.Migration
{
    [Migration(20260303143400)]
    public class DB_20260303_143400_RoleMaster : AutoReversingMigration
    {
        public override void Up()
        {
            Create.Table("role")
                .WithColumn("id").AsCustom("INTEGER GENERATED BY DEFAULT AS IDENTITY").PrimaryKey()
                .WithColumn("row_id").AsFixedLengthString(30).Unique("UK_ROLE_ID")
                .WithColumn("role_name").AsString().NotNullable().Unique("UK_ROLE_NAME")
                .WithColumn("is_active").AsBoolean().WithDefaultValue(true).NotNullable()
                .WithColumn("created_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("created_by").AsInt32().NotNullable()
                .WithColumn("updated_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("updated_by").AsInt32().NotNullable();


            Create.ForeignKey("FK_ROLE_CREATED_BY_USER")
                .FromTable("role").ForeignColumn("created_by")
                .ToTable("user").PrimaryColumn("id");

            Create.ForeignKey("FK_ROLE_UPDATED_BY_USER")
                .FromTable("role").ForeignColumn("updated_by")
                .ToTable("user").PrimaryColumn("id");


            //adding one default role as administrator
            var _dateTime = System.DateTime.Now.ToUniversalTime();
            Insert.IntoTable("role")
                .Row(new
                {
                    id = 1,
                    row_id = Ulid.NewUlid().ToString(),
                    role_name = "Administrator",
                    is_active = true,
                    created_at = _dateTime,
                    created_by = 1,
                    updated_at = _dateTime,
                    updated_by = 1
                });

            // alter user table and add role_id to default user
            Alter.Table("user")
                .AddColumn("role_id").AsInt32().Nullable();

            //create foreigh key
            Create.ForeignKey("FK_USER_ROLE_ID_ROLE")
                .FromTable("user").ForeignColumn("role_id")
                .ToTable("role").PrimaryColumn("id");

        }
    }
}
