using FluentMigrator;

namespace MindEarth.Web.Migration
{
    [Migration(20260301074001)]
    public class DB_20260301_074000_MenuMaster : AutoReversingMigration
    {
        public override void Up()
        {
            Create.Table("menu")
                .WithColumn("id").AsCustom("INTEGER GENERATED BY DEFAULT AS IDENTITY").PrimaryKey()
                .WithColumn("row_id").AsFixedLengthAnsiString(50).NotNullable().Unique("UK_MENU_ROW_ID")
                .WithColumn("text").AsString().NotNullable()
                .WithColumn("controller").AsString().NotNullable()
                .WithColumn("page_url").AsString().Nullable()
                .WithColumn("seq_no").AsInt16().NotNullable()
                .WithColumn("is_active").AsBoolean().NotNullable().WithDefaultValue(true)
                .WithColumn("created_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("created_by").AsInt32().NotNullable()
                .WithColumn("updated_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("updated_by").AsInt32().NotNullable();

            Create.ForeignKey("FK_MENU_CREATED_BY_USER")
                .FromTable("menu").ForeignColumn("created_by")
                .ToTable("user").PrimaryColumn("id");

            Create.ForeignKey("FK_MENU_UPDATED_BY_USER")
                .FromTable("menu").ForeignColumn("updated_by")
                .ToTable("user").PrimaryColumn("id");

            Create.Table("menu_detail")
                .WithColumn("id").AsInt32().PrimaryKey().Identity().NotNullable()
                .WithColumn("row_id").AsFixedLengthAnsiString(50).NotNullable().Unique("UK_MENU_DETAIL_ROW_ID")
                .WithColumn("menu_id").AsInt32().NotNullable()
                .WithColumn("text").AsString().NotNullable()
                .WithColumn("page_url").AsString().NotNullable()
                .WithColumn("seq_no").AsInt16().NotNullable()
                .WithColumn("is_active").AsBoolean().NotNullable().WithDefaultValue(true)
                .WithColumn("created_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("created_by").AsInt32().NotNullable()
                .WithColumn("updated_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("updated_by").AsInt32().NotNullable();

            Create.ForeignKey("FK_MENU_DETAIL_CREATED_BY_USER")
                .FromTable("menu_detail").ForeignColumn("created_by")
                .ToTable("user").PrimaryColumn("id");

            Create.ForeignKey("FK_MENU_DETAIL_UPDATED_BY_USER")
                .FromTable("menu_detail").ForeignColumn("updated_by")
                .ToTable("user").PrimaryColumn("id");

            Create.ForeignKey("FK_MENU_DETAIL_MENU_ID")
                .FromTable("menu_detail").ForeignColumn("menu_id")
                .ToTable("menu").PrimaryColumn("id");

            Create.UniqueConstraint("UK_MENU_DETAIL_TEXT_MENU_ID")
                .OnTable("menu_detail").Columns("text", "menu_id");
        }
    }
}
