using FluentMigrator;

namespace MindEarth.Web.Migration
{
    [Migration(20260220194200)]
    public class DB_20260220_194200_UserCreation : AutoReversingMigration
    {
        public override void Up()
        {
            Create.Table("user")
                .WithColumn("id").AsCustom("INTEGER GENERATED BY DEFAULT AS IDENTITY").PrimaryKey()
                .WithColumn("row_id").AsFixedLengthString(26).Unique("UK_USER_ROW_ID").WithDefaultValue(Ulid.NewUlid().ToString()).NotNullable()
                .WithColumn("first_name").AsString().NotNullable()
                .WithColumn("last_name").AsString().NotNullable()
                .WithColumn("email").AsString().NotNullable().Unique("UK_USER_EMAIL")
                .WithColumn("salt").AsString().NotNullable().WithDefaultValue(Guid.NewGuid().ToString())
                .WithColumn("password").AsString().NotNullable()
                .WithColumn("is_active").AsBoolean().WithDefaultValue(false).NotNullable()
                .WithColumn("created_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("created_by").AsInt32().NotNullable()
                .WithColumn("updated_at").AsDateTime().WithDefault(SystemMethods.CurrentUTCDateTime).NotNullable()
                .WithColumn("updated_by").AsInt32().NotNullable();

            //adding the default user
            var _salt = Guid.NewGuid().ToString();
            var _dateTime = System.DateTime.Now.ToUniversalTime();
            var passWordSalt = $"Admin@1234{_salt}";
            var _password = BCrypt.Net.BCrypt.HashPassword(passWordSalt);
            Insert.IntoTable("user")
                .Row(new {
                    id = 1,
                    row_id = Ulid.NewUlid().ToString(),
                    first_name = "Mind Earth Admin",
                    last_name = "Pune India",
                    email = "info@mindearth.com",
                    salt = _salt,
                    password = _password,
                    is_active = true,
                    created_at = _dateTime,
                    created_by = 1,
                    updated_at = _dateTime,
                    updated_by = 1
                });
        }
    }
}
